name: RPM Signing Workflow

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      options: --privileged
      image: ghcr.io/perfsonar/docker-oneshot-builder/ol8:latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y rpm gnupg2

      - name: Generate GPG key pair
        run: |
          gpg --batch --generate-key --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" <<EOF
          Key-Type: default
          Subkey-Type: default
          Name-Real: GitHub Actions
          Name-Comment: GitHub Actions
          Name-Email: actions@example.com
          Expire-Date: 0
          %commit
          EOF

      - name: Set up GPG
        run: echo "allow-loopback-pinentry" >> ~/.gnupg/gpg.conf

      - name: Create RPM package
        run: |
          echo "Creating a simple RPM package..."
          mkdir -p mypackage-1.0
          echo "Version: 1.0" > mypackage-1.0/metadata.txt

          cat <<EOF > mypackage.spec
          Name: mypackage
          Version: 1.0
          Release: 1
          Summary: My Package
          License: MIT

          %description
          This is a simple package.

          %prep
          echo "Hello, this is the %prep section."

          %files
          %defattr(-,root,root,-)
          /metadata.txt
          
          %changelog
          * Tue Apr  5 2024 Mike Jordan <mj23@bulls.com> 1.0-1
          - Initial version
          EOF

      - name: RPM build
        run: |              
          pwd
          ls -al 
          ls -al mypackage-1.0
          rpmbuild --define '_topdir /home/runner/work/gpg-sign-example/gpg-sign-example/BUILDROOT' --define "_rpmdir /home/runner/work/gpg-sign-example/gpg-sign-example/BUILDROOT" --define "_builddir /home/runner/work/gpg-sign-example/gpg-sign-example/BUILDROOT" --define "_sourcedir /home/runner/work/gpg-sign-example/gpg-sign-example/BUILDROOT " -bb mypackage.spec
 
          mv *.rpm mypackage-1.0.rpm

      - name: Sign RPM
        run: |
          echo "Signing RPM..."
          gpg --batch --yes --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --detach-sign mypackage-1.0.rpm

      - name: Display RPM info
        run: |
          echo "Displaying RPM info..."
          rpm -qi mypackage-1.0.rpm
